src/Entity/Circle.php
<?php

namespace App\Entity;

use App\Repository\CircleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CircleRepository::class)]
class Circle
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $postcode = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $country = null;

    #[ORM\ManyToOne(inversedBy: 'ownedCircles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $created_by = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    /**
     * @var Collection<int, UserCircle>
     */
    #[ORM\OneToMany(targetEntity: UserCircle::class, mappedBy: 'circle', cascade: ['persist'], orphanRemoval: true)]
    private Collection $userCircles;

    #[ORM\Column(length: 255)]
    private ?string $short_id = null;

    /**
     * @var Collection<int, ItemCircle>
     */
    #[ORM\OneToMany(targetEntity: ItemCircle::class, mappedBy: 'circle', cascade: ['persist'], orphanRemoval: true)]
    private Collection $itemCircles;

    #[ORM\Column(length: 255, nullable: false)]
    private ?string $circle_type = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $insee_code = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lat = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lng = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $AddressLabel = null;


    public function __construct()
    {
        $this->userCircles = new ArrayCollection();
        $this->itemCircles = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(?string $postcode): static
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): static
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, UserCircle>
     */
    public function getUserCircles(): Collection
    {
        return $this->userCircles;
    }

    public function addUserCircle(UserCircle $userCircle): static
    {
        if (!$this->userCircles->contains($userCircle)) {
            $this->userCircles->add($userCircle);
            $userCircle->setCircle($this);
        }

        return $this;
    }

    public function removeUserCircle(UserCircle $userCircle): static
    {
        if ($this->userCircles->removeElement($userCircle)) {
            // set the owning side to null (unless already changed)
            if ($userCircle->getCircle() === $this) {
                $userCircle->setCircle(null);
            }
        }

        return $this;
    }

    public function getShortId(): ?string
    {
        return $this->short_id;
    }

    public function setShortId(string $short_id): static
    {
        $this->short_id = $short_id;

        return $this;
    }

    /**
     * @return Collection<int, ItemCircle>
     */
    public function getItemCircles(): Collection
    {
        return $this->itemCircles;
    }

    public function addItemCircle(ItemCircle $itemCircle): static
    {
        if (!$this->itemCircles->contains($itemCircle)) {
            $this->itemCircles->add($itemCircle);
            $itemCircle->setCircle($this);
        }

        return $this;
    }

    public function removeItemCircle(ItemCircle $itemCircle): static
    {
        if ($this->itemCircles->removeElement($itemCircle)) {
            // set the owning side to null (unless already changed)
            if ($itemCircle->getCircle() === $this) {
                $itemCircle->setCircle(null);
            }
        }

        return $this;
    }

    public function getCircleType(): ?string
    {
        return $this->circle_type;
    }

    public function setCircleType(?string $circle_type): static
    {
        $this->circle_type = $circle_type;

        return $this;
    }

    public function getInseeCode(): ?string
    {
        return $this->insee_code;
    }

    public function setInseeCode(?string $insee_code): static
    {
        $this->insee_code = $insee_code;

        return $this;
    }

    public function getLat(): ?string
    {
        return $this->lat;
    }

    public function setLat(?string $lat): static
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?string
    {
        return $this->lng;
    }

    public function setLng(?string $lng): static
    {
        $this->lng = $lng;

        return $this;
    }

    public function getAddressLabel(): ?string
    {
        return $this->AddressLabel;
    }

    public function setAddressLabel(string $AddressLabel): static
    {
        $this->AddressLabel = $AddressLabel;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\PasswordStrength;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'Un compte existe déjà avec cette adresse email.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private bool $isVerified = false;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $phone = null;

    /**
     * @var Collection<int, Circle>
     */
    #[ORM\OneToMany(targetEntity: Circle::class, mappedBy: 'created_by')]
    private Collection $ownedCircles;

    /**
     * @var Collection<int, UserCircle>
     */
    #[ORM\OneToMany(targetEntity: UserCircle::class, mappedBy: 'user_id', cascade: ['persist'], orphanRemoval: true)]
    private Collection $userCircles;


    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at;

    /**
     * @var Collection<int, Item>
     */
    #[ORM\OneToMany(targetEntity: Item::class, mappedBy: 'owner', cascade: ['persist'], orphanRemoval: true)]
    private Collection $items;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $last_name = null;

    public function __construct()
    {
        $this->ownedCircles = new ArrayCollection();
        $this->userCircles = new ArrayCollection();
        $this->items = new ArrayCollection();
    }

    public function __toString()
    {
        $nickname = $this->email;
        if(null !== $this->first_name || null !== $this->last_name){
            $nickname = $this->first_name . ' ' . $this->last_name . ' ('. $this->email .')';
        }
        return $nickname;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Circle>
     */
    public function getOwnedCircles(): Collection
    {
        return $this->ownedCircles;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection<int, UserCircle>
     */
    public function getUserCircles(): Collection
    {
        return $this->userCircles;
    }

    public function addUserCircle(UserCircle $userCircle): static
    {
        if (!$this->userCircles->contains($userCircle)) {
            $this->userCircles->add($userCircle);
            $userCircle->setUserId($this);
        }

        return $this;
    }

    public function removeUserCircle(UserCircle $userCircle): static
    {
        if ($this->userCircles->removeElement($userCircle)) {
            // set the owning side to null (unless already changed)
            if ($userCircle->getUserId() === $this) {
                $userCircle->setUserId(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Item>
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): static
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
            $item->setOwner($this);
        }

        return $this;
    }

    public function removeItem(Item $item): static
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getOwner() === $this) {
                $item->setOwner(null);
            }
        }

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }
}

templates/app_circle/circle_list_component.html.twig
{# <ul class="list-group list-group-flush my-2">
    {% for userCircle in userCircles %}  
        <div class="list-group-item  d-flex align-items-center" >
            <div class="ms-2 me-auto">
                <div class="fw-bold">{{userCircle.circle.name}}
                {% if userCircle.circle.createdBy == app.user %}<span class="fw-light">(propriétaire)</span>{% endif %}
                 </div>
            </div>
            <div class="">
              <button 
                class="btn btn-sm btn-info btn-share-circle"  
                data-bs-target="#shareCircleModal" 
                data-circle-uri="{{url('app_circle_join_identified', {shortId : userCircle.circle.shortId})}}" 
                data-circle-name="{{userCircle.circle.name}}" 
              >
              <i class="bi bi-share-fill me-2"></i>Partager</button>
            </div>
        </div>
    {% else %}
      Vous n'avez pas encore rejoint de boîte à partage. Vous pouvez en créer une ou en rejoindre une.
    {% endfor %}
</ul>
 #}
{% set circleTypes = {
    'building': 'Une Résidence ou un immeuble',
    'district': 'Un quartier',
    'village': 'Un hameau ou un village',
    'company': 'Une entreprise',
    'association': 'Une association',
    'other': 'Autre'
  } 
%}
<div class="accordion accordion-flush" id="accordionCircles">
  {% for userCircle in userCircles %}  
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#circle{{loop.index}}" aria-expanded="false" aria-controls="circle{{loop.index}}">
          <div class="fw-bold">{{userCircle.circle.name}}
            {% if userCircle.circle.createdBy == app.user %}<span class="fw-light">(propriétaire)</span>{% endif %}
          </div>
      </h2>
      <div id="circle{{loop.index}}" class="accordion-collapse collapse" data-bs-parent="#accordionCircles">
        <div class="accordion-body d-flex flex-column">
          <div class="card">
            <div class="card-body">
              <div class="mb-1 fw-bold">
                Localisation
              </div>
              <div class="mb-2">
                {{userCircle.circle.addressLabel}}
              </div>
              <div class="mb-1 fw-bold">
                Type de boîte
              </div>
              <div class="mb-2">
                {{circleTypes[userCircle.circle.circleType]}}
              </div>
              <div class="d-flex align-items-center mt-3 justify-content-end">
                {% if userCircle.circle.createdBy == app.user %}
                  <button 
                    class="btn btn-sm btn-outline-info btn-generate-flyer me-2"  
                    data-bs-target="#generateFlyerModal" 
                    data-circle-uri="{{url('app_circle_join_identified', {shortId : userCircle.circle.shortId})}}" 
                    data-circle-name="{{userCircle.circle.name}}" 
                    data-circle-short-id="{{userCircle.circle.shortId}}" 
                    data-circle-type="{{userCircle.circle.circleType}}" 
                    data-circle-owner-first-name="{{app.user.firstName}}" 
                    data-circle-owner-last-name="{{app.user.lastName}}" 
                    >
                    <i class="bi bi-file-richtext me-2"></i>Générer un flyer
                  </button>
                  <div class="d-none" id="logoImgSrc" data-url="{{asset('img/logo-bleu-petard.jpg')}}"></div>
                  <div class="d-none" id="globeImgSrc" data-url="{{asset('img/globe.png')}}"></div>
                  <div class="d-none" id="mouseImgSrc" data-url="{{asset('img/mouse.png')}}"></div>
                  <div class="d-none" id="priseEnMainImgSrc" data-url="{{asset('img/prise-en-main.png')}}"></div>
                {% endif %}
              
                <button 
                  class="btn btn-sm btn-info btn-share-circle "  
                  data-bs-target="#shareCircleModal" 
                  data-circle-uri="{{url('app_circle_join_identified', {shortId : userCircle.circle.shortId})}}" 
                  data-circle-name="{{userCircle.circle.name}}" 
                  >
                  <i class="bi bi-share-fill me-2"></i>Partager
                </button>
              </div>
            </div>
          </div>
          
        </div>

      </div>
    </div>
    {% endfor %}
</div>
<!-- Share Modal -->
<div class="modal fade" id="shareCircleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>

<!-- Flyer Modal -->
<div class="modal fade" id="generateFlyerModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <a class="btn btn-info btn-download-flyer" href=""><i class="bi bi-file-earmark-arrow-down me-2"></i>Télécharger le flyer</a>
        {# <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button> #}
      </div>
    </div>
  </div>
</div>

templates/app_circle/create.html.twig
{% extends 'base_auth.html.twig' %}

{% block title %}Créer une boîte{% endblock %}

{% block body %}
<div class="container">
    <div class="p-2 p-lg-5 my-1 my-lg-4 col-md-6 offset-md-3">
    
        {% for flash_error in app.flashes('verify_email_error') %}
            <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
        {% endfor %}
        <h1 class="fw-bold mb-3">Créer une boîte à partage</h1>
        {{ form_errors(form) }}
        {{ form_start(form) }}
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}
{% block javascripts %}
    {% block importmap %}
     {{ importmap(['app', 'select']) }}
    {% endblock %}
{% endblock %}

templates/app_circle/index.html.twig
{% extends 'base_auth.html.twig' %}

{% block title %}Boîtes à partage{% endblock %}

{% block body %}

{% set circleTypes = {
    'building': 'Une Résidence ou un immeuble',
    'district': 'Un quartier',
    'village': 'Un hameau ou un village',
    'company': 'Une entreprise',
    'association': 'Une association',
    'other': 'Autre'
  } 
%}

<div class="container">
  <div class="px-lg-5">
    <div class="container-fluid py-5">
      <div class="d-flex align-items-center justify-content-between">
          <h1 class="display-5 fw-bold">Vos boîtes</h1>
          <a class="btn btn-primary px-4"  href="{{path('app_circle_create')}}" role="button"><i class="bi bi-plus-circle me-2"></i>Créer une boîte</a>
      </div>
      <div class="row row-cols-1 row-cols-md-2 g-4 mt-3">
        {% for userCircle in userCircles %}  
        <div class="col">
          <div class="card">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <div class="fw-bold fs-4">
                  {{userCircle.circle.name}} {% if userCircle.circle.createdBy == app.user %}<span class="fw-light fs-6">(propriétaire)</span>{% endif %}
                </div>
                <a class="link-dark ms-auto card-more-info collapsed" data-bs-toggle="collapse" href="#circleInfo{{loop.index}}" role="button" aria-expanded="false" aria-controls="circleInfo{{loop.index}}">
                  <i class="bi bi-chevron-down"></i>
                </a>
              </div>
              <div class="collapse" id="circleInfo{{loop.index}}">
                <div class="mt-2 fw-bold">
                  Type de boîte
                </div>
                <div class="mt-1">
                  {{circleTypes[userCircle.circle.circleType]}}
                </div>
                <div class="fw-bold mt-2">
                  Localisation
                </div>
                <div class="mt-1">
                  {{userCircle.circle.addressLabel}}
                </div>
              </div>
              <div class="d-flex align-items-center mt-3 justify-content-end">
                {% if userCircle.circle.createdBy == app.user %}
                  <button 
                    class="btn btn-sm btn-outline-info btn-generate-flyer me-2"  
                    data-bs-target="#generateFlyerModal" 
                    data-circle-uri="{{url('app_circle_join_identified', {shortId : userCircle.circle.shortId})}}" 
                    data-circle-name="{{userCircle.circle.name}}" 
                    data-circle-short-id="{{userCircle.circle.shortId}}" 
                    data-circle-type="{{userCircle.circle.circleType}}" 
                    data-circle-owner-first-name="{{app.user.firstName}}" 
                    data-circle-owner-last-name="{{app.user.lastName}}" 
                    >
                    <i class="bi bi-file-richtext me-2"></i>Générer un flyer
                  </button>
                  <div class="d-none" id="logoImgSrc" data-url="{{asset('img/logo-bleu-petard.jpg')}}"></div>
                  <div class="d-none" id="globeImgSrc" data-url="{{asset('img/globe.png')}}"></div>
                  <div class="d-none" id="mouseImgSrc" data-url="{{asset('img/mouse.png')}}"></div>
                  <div class="d-none" id="priseEnMainImgSrc" data-url="{{asset('img/prise-en-main.png')}}"></div>
                {% endif %}
              
                <button 
                  class="btn btn-sm btn-info btn-share-circle "  
                  data-bs-target="#shareCircleModal" 
                  data-circle-uri="{{url('app_circle_join_identified', {shortId : userCircle.circle.shortId})}}" 
                  data-circle-name="{{userCircle.circle.name}}" 
                  >
                  <i class="bi bi-share-fill me-2"></i>Partager
                </button>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{# Share modal #}
<div class="modal fade" id="shareCircleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>

{# Flyer modal #}
<div class="modal fade" id="generateFlyerModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <a class="btn btn-info btn-download-flyer" href=""><i class="bi bi-file-earmark-arrow-down me-2"></i>Télécharger le flyer</a>
        {# <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button> #}
      </div>
    </div>
  </div>
</div>


{# <div class="container">
  <div class="row">
    <div class="col-md-6 p-5 my-4 ">
      <div class=" p-5 ">
        <h1 class="fs-3 fw-bold mb-4">Boîtes à partage</h1>
        {{ include('app_circle/circle_list_component.html.twig') }}
      </div>
    </div>
  </div>
<p class="result"></p>
</div> #}
{% endblock %}
{% block javascripts %}
    {% block importmap %}
     {{ importmap(['app', 'shareCircle', 'generateFlyer']) }}
    {% endblock %}
{% endblock %}

templates/app_circle/join.html.twig
{% extends 'base_auth.html.twig' %}

{% block title %}Rejoindre une boîte{% endblock %}

{% block body %}
<div class="container">
    <div class="p-5 my-4   col-md-6 offset-md-3">
        {% for flash_error in app.flashes('verify_email_error') %}
            <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
        {% endfor %}
        <h1 class="fw-bold mb-3">Rejoindre une boîte à partage</h1>
        {{ form_errors(form) }}
        {{ form_start(form) }}
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/app_circle/show.html.twig
{% extends 'base_auth.html.twig' %}

{% block title %}Recherche Boîtes à partage{% endblock %}

{% block body %}
<div class="container">
    <div class="px-2 py-2 my-4  ">
      <div class="container-fluid py-3">
        <div class="d-flex align-items-center justify-content-between">
            <h1 class="display-5 fw-bold">Rechercher un objet</h1>
        </div>
        {% if items|length == 0 %}
            <div class="mt-4">
                <p class="fs-4" >Il n'y a pas encore d'objet dans cette boîte. <a href="{{path('app_item_create')}}">Ajoutez-en un</a> maintenant.</p>
            </div>
        {% endif %}
        {% if items|length > 0 %}
            <div class="mt-4">
                <div class="col-12 pt-3 pb-2">
                    <input type="text" id="filterItemTableInput" focused class="form-control" placeholder="Taper pour chercher" aria-label="Rechercher un élément" aria-describedby="externalFilter" value="{{searchTerms}}">
                </div>
                <table class="table table-striped table-hover" id="itemTable">
                    <thead>
                        <tr>
                        <th scope="col">Catégorie</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Prop 2</th>
                        <th scope="col">Propriétaire</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in items %}  
                            <tr>
                                <td>{{item.typeLabel}}</td>
                                <td>{{item.property_1}}</td>
                                <td>{{item.property_2}}</td>
                                <td>{{item.owner}}</td>
                            </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>
        {% endif %}
      </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
    {% block importmap %}
     {{ importmap(['app', 'searchItem']) }}
    {% endblock %}
{% endblock %}