src/Entity/Item.php
<?php

namespace App\Entity;

use App\Repository\ItemRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ItemRepository::class)]
class Item
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'items')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    /**
     * @var Collection<int, ItemCircle>
     */
    #[ORM\OneToMany(targetEntity: ItemCircle::class, mappedBy: 'item', cascade: ['persist'], orphanRemoval: true)]
    private Collection $itemCircles;

    #[ORM\ManyToOne(inversedBy: 'items')]
    private ?itemType $itemType = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $property_1 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $property_2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $property_3 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $property_4 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $property_5 = null;

    public function __construct()
    {
        $this->itemCircles = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->property_1;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, ItemCircle>
     */
    public function getItemCircles(): Collection
    {
        return $this->itemCircles;
    }

    public function addItemCircle(ItemCircle $itemCircle): static
    {
        if (!$this->itemCircles->contains($itemCircle)) {
            $this->itemCircles->add($itemCircle);
            $itemCircle->setItem($this);
        }

        return $this;
    }

    public function removeItemCircle(ItemCircle $itemCircle): static
    {
        if ($this->itemCircles->removeElement($itemCircle)) {
            // set the owning side to null (unless already changed)
            if ($itemCircle->getItem() === $this) {
                $itemCircle->setItem(null);
            }
        }

        return $this;
    }

    public function getItemType(): ?itemType
    {
        return $this->itemType;
    }

    public function setItemType(?itemType $itemType): static
    {
        $this->itemType = $itemType;

        return $this;
    }

    public function getProperty1(): ?string
    {
        return $this->property_1;
    }

    public function setProperty1(?string $property_1): static
    {
        $this->property_1 = $property_1;

        return $this;
    }

    public function getProperty2(): ?string
    {
        return $this->property_2;
    }

    public function setProperty2(?string $property_2): static
    {
        $this->property_2 = $property_2;

        return $this;
    }

    public function getProperty3(): ?string
    {
        return $this->property_3;
    }

    public function setProperty3(?string $property_3): static
    {
        $this->property_3 = $property_3;

        return $this;
    }

    public function getProperty4(): ?string
    {
        return $this->property_4;
    }

    public function setProperty4(?string $property_4): static
    {
        $this->property_4 = $property_4;

        return $this;
    }

    public function getProperty5(): ?string
    {
        return $this->property_5;
    }

    public function setProperty5(?string $property_5): static
    {
        $this->property_5 = $property_5;

        return $this;
    }
}

src/Controller/AppItemController.php
<?php

namespace App\Controller;

use App\Entity\Item;
use App\Entity\ItemCircle;
use App\Entity\ItemType;
use App\Form\ItemFormType;
use App\Form\ItemBookFormType;
use DateTime;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class AppItemController extends AbstractController
{
    #[Route('/app/placard', name: 'app_items')]
    public function index(EntityManagerInterface $em): Response
    {
        $user = $this->getUser();
        $userItems = $em->getRepository(Item::class)->findBy(['owner' => $user->getId()]);
        return $this->render('app_item/index.html.twig', [
            'controller_name' => 'AppObjectController',
            'userItems' => $userItems
        ]);
    }

    /*
    #[Route('/app/placard/ajoutsave', name: 'app_item_create_save')]
    public function createItemSave(Request $request, EntityManagerInterface $em): Response
    {
        $item = new Item();
        $user = $this->getUser();
        $item->setOwner($user);
        $form = $this->createForm(ItemFormType::class, $item);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $nextAction = $form->get('submitAndAdd')->isClicked()
                ? 'app_item_create'
                : 'app_items';
            $item->setCreatedAt(new DateTimeImmutable('now'));
            $em->persist($item);

            //handle itemCircle
            //get all circles of the user
            $userCircles = $user->getUserCircles();
            foreach ($userCircles as &$userCircle) {
                $circle = $userCircle->getCircle();
                $itemCircle = new ItemCircle(); //create itemCircle
                $itemCircle->setCircle($circle); //populate circle
                $itemCircle->setItem($item); //populate item
                $em->persist($itemCircle); //persist
            }

            $em->flush();

            $this->addFlash('success', 'L\'objet a bien été ajouté à votre placard.');

            if($nextAction === 'app_item_create'){
                $previousItemType = $item->getItemType();
                $item = new Item();
                $item->setItemType($previousItemType);
                $form = $this->createForm(ItemFormType::class, $item);

                return $this->render('app_item/create_update.html.twig', [
                    'controller_name' => 'AppCircleController',
                    'form' => $form
                ]);
            } else {
                return $this->redirectToRoute($nextAction);
            }
        }


        return $this->render('app_item/create_update.html.twig', [
            'controller_name' => 'AppCircleController',
            'form' => $form
        ]);
    }
    */
    #[Route('/app/placard/ajout', name: 'app_item_create')]
    public function createItem(Request $request, EntityManagerInterface $em): Response
    {
        return $this->render('app_item/create/index.html.twig', [
            'controller_name' => 'AppCircleController'
        ]);
    }

    #[Route('/app/placard/ajout/livre', name: 'app_item_create_book')]
    public function createBookItem(Request $request, EntityManagerInterface $em): Response
    {
        $item = new Item();
        $itemType = $em->getRepository(ItemType::class)->findOneBy(['code' => 'book']);
        $item->setItemType($itemType);
        $user = $this->getUser();
        $item->setOwner($user);
        $form = $this->createForm(ItemBookFormType::class, $item);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $nextAction = 'app_items';
            if(true === $form->get('submitAndAdd')->isClicked()) {
                $nextAction = 'app_item_create_book';
            }
            $item->setCreatedAt(new DateTimeImmutable('now'));
            $em->persist($item);

            //handle itemCircle
            //get all circles of the user
            $userCircles = $user->getUserCircles();
            foreach ($userCircles as &$userCircle) {
                $circle = $userCircle->getCircle();
                $itemCircle = new ItemCircle(); //create itemCircle
                $itemCircle->setCircle($circle); //populate circle
                $itemCircle->setItem($item); //populate item
                $em->persist($itemCircle); //persist
            }

            $em->flush();

            $this->addFlash('success', 'Le livre a bien été ajouté à votre placard.');

            if($nextAction === 'app_item_create'){
                $previousItemType = $item->getItemType();
                $item = new Item();
                $item->setItemType($previousItemType);
                $form = $this->createForm(ItemBookFormType::class, $item);

                return $this->render('app_item/create/book.html.twig', [
                    'controller_name' => 'AppCircleController',
                    'form' => $form
                ]);
            } else {
                return $this->redirectToRoute($nextAction);
            }
        }


        return $this->render('app_item/create/book.html.twig', [
            'controller_name' => 'AppCircleController',
            'form' => $form
        ]);
    }

    #[Route('/app/placard/{id}/update', name: 'app_item_update', requirements: ['id' => '\d+'])]
    public function updateItem(Request $request, EntityManagerInterface $em, int $id): Response
    {
        $item = $em->getRepository(Item::class)->find($id);
        if (!$item) {
            throw $this->createNotFoundException(
                'L\'objet n\'a pas été trouvé'
            );
        }

        $user = $this->getUser();
        $form = $this->createForm(ItemFormType::class, $item, [
            'update_mode' => true,
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            
            $em->persist($item);
            $em->flush();
            $this->addFlash('success', 'L\'objet a bien été mis à jour');
            return $this->redirectToRoute('app_items');
        }


        return $this->render('app_item/create_update.html.twig', [
            'controller_name' => 'AppCircleController',
            'form' => $form,
            'updateMode' => true
        ]);
    }

    #[Route('/app/placard/{id}/delete', name: 'app_item_delete', requirements: ['id' => '\d+'])]
    public function deleteItem(Request $request, EntityManagerInterface $em, int $id): Response
    {
        $item = $em->getRepository(Item::class)->find($id);
        if (!$item) {
            throw $this->createNotFoundException(
                'L\'objet n\'a pas été trouvé'
            );
        }
        $em->remove($item);
        $em->flush();
        $this->addFlash('success', 'L\'objet a bien été supprimé');
        return $this->redirectToRoute('app_items');
    }
}

templates/app_item/create.html.twig
{% extends 'base_auth.html.twig' %}

{% block title %}Ajout au Placard{% endblock %}

{% block body %}
<div class="container">
    <div class="p-5 my-4 bg-body-tertiary rounded-3 col-md-6 offset-md-3">
        {% for flash_error in app.flashes('verify_email_error') %}
            <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
        {% endfor %}
        <h1 class="fw-bold mb-3">Ajouter un objet à partager</h1>
        <div
            class="alert alert-info"
            role="alert"
        >
            <div class="d-flex justify-content-start">
                <span class="me-3"><i class="bi bi-info-circle"></i></span>
                <span>Veuillez noter que par défaut, si vous appartenez à plusieurs cercles, <strong>tous les éléments de votre placard seront partagés avec tous vos cercles</strong>.</span>
            </div>
        </div>
                {{ form_errors(form) }}
        {{ form_start(form) }}
            {{ form_row(form.description, {
                label: 'Description',
                help: 'maximum 255 caractères'
            }) }}
            {{ form_row(form.category, {
                label: 'Catégorie'
            }) }}
            <div class="row ">
                <div class="col d-flex justify-content-end">
                    {{ form_row(form.submit, {
                        label: 'Ajouter'
                    }) }}
                    <div class="ms-2">
                    {{ form_row(form.submitAndAdd, {
                        label: 'Ajouter et ajouter un autre'
                    }) }}
                    </div>
                </div>
            </div>
            
            
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/app_item/create_update.html.save.twig
{% extends 'base_auth.html.twig' %}

{% block title %}Ajout au Placard{% endblock %}

{% block body %}

<div class="container">
    <div class="p-2 p-lg-5 col-md-6 offset-md-3">
        {% for flash_error in app.flashes('verify_email_error') %}
            <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
        {% endfor %}
        <h1 class="fw-bold mb-3">{% if updateMode|default(false) %}Mettre à jour un objet{% else %}Ajouter un objet au placard{% endif %}</h1>
        <div
            class="alert alert-warning  d-none"
            role="alert"
        >
            <div class="d-flex justify-content-start">
                <span class="me-3"><i class="bi bi-info-circle"></i></span>
                <span>Veuillez noter que par défaut, si vous avez rejoint plusieurs boîtes, <strong>tous les éléments</strong> de votre placard seront partagés dans <strong>toutes vos boîtes</strong>.</span>
            </div>
        </div>
                {{ form_errors(form) }}
        {{ form_start(form) }}
            {{ form_row(form.description, {
                label: 'Description',
                attr :{
                    "autofocus":"true"
                },
                help: 'Ajoutez un maximum de précision sur l\'objet (max 255 caractères)'
            }) }}
            {{ form_row(form.category, {
                label: 'Catégorie'
            }) }}
            <div class="row ">
                <div class="col d-flex justify-content-end">
                    {{ form_row(form.submit) }}
                    <div class="ms-2">
                    {{ form_row(form.submitAndAdd) }}
                    </div>
                </div>
            </div>
            
            
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/app_item/create_update.html.twig
{% extends 'base_auth.html.twig' %}

{% block title %}Ajout au Placard{% endblock %}

{% block body %}

<div class="container">
    <div class="p-2 p-lg-5 col-md-6 offset-md-3">
        {% for flash_error in app.flashes('verify_email_error') %}
            <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
        {% endfor %}
        <h1 class="fw-bold mb-3">{% if updateMode|default(false) %}Mettre à jour un objet{% else %}Ajouter un objet au placard{% endif %}</h1>
        <div
            class="alert alert-warning  d-none"
            role="alert"
        >
            <div class="d-flex justify-content-start">
                <span class="me-3"><i class="bi bi-info-circle"></i></span>
                <span>Veuillez noter que par défaut, si vous avez rejoint plusieurs boîtes, <strong>tous les éléments</strong> de votre placard seront partagés dans <strong>toutes vos boîtes</strong>.</span>
            </div>
        </div>
        {{ form_errors(form) }}
        {{ form_start(form) }}
            {{ form_row(form.itemType, {
                label: 'Catégorie'
            }) }}
            {{ form_row(form.property_1, {
                label: 'Description',
                attr :{
                    "autofocus":"true"
                },
                help: 'Ajoutez un maximum de précision sur l\'objet (max 255 caractères)'
            }) }}
            <div class="row ">
                <div class="col d-flex justify-content-end">
                    {{ form_row(form.submitAndAdd) }}
                    <div class="ms-2">
                        {{ form_row(form.submit) }}
                    </div>
                </div>
            </div>
        {{ form_end(form) }}
</div>
{% endblock %}

templates/app_item/index.html.twig
{% extends 'base_auth.html.twig' %}

{% block title %}Mon Placard{% endblock %}

{% block body %}
<div class="container">
    <div class="px-lg-5">
      <div class="container-fluid py-5">
        <div class="d-flex align-items-center justify-content-between">
            <h1 class="display-5 fw-bold">Votre placard</h1>
            <a class="btn btn-primary px-4"  href="{{path('app_item_create')}}" role="button"><i class="bi bi-plus-circle me-2"></i>Ajouter un objet</a>
        </div>
        {% if userItems|length == 0 %}
            <div class="mt-4">
                <p class="fs-4" >Votre placard est vide. Commencez par <a class=""  href="{{path('app_item_create')}}" role="button">ajouter un objet</a>.</p>
            </div>
        {% endif %}
        {% if userItems|length > 0 %}
            <div class="mt-4">
                <div class="col-12 pt-3 pb-2">
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="externalFilter">Rechercher un objet</span>
                            <input type="text" id="filterItemTableInput" class="form-control" placeholder="Visseuse" aria-label="Rechercher un objet" aria-describedby="externalFilter">
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover" id="itemTable">
                    <thead>
                        <tr>
                        <th scope="col">Objet</th>
                        <th scope="col">Catégorie</th>
                        <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for userItem in userItems %}  
                            <tr>
                                <td>{{userItem.property1}}</td>
                                <td>{{userItem.itemType ? userItem.itemType.label}}</td>
                                <td class="justify-content-end d-flex">
                                    <a href="{{path('app_item_update', {id: userItem.id})}}" class="btn btn-sm btn-outline-secondary border-0 me-2" data-bs-toggle="tooltip" data-bs-title="Éditer"><i class="bi bi-pencil-fill"></i></a>
                                    <span href="#" class="me-2" data-bs-toggle="tooltip" data-bs-title="Supprimer">
                                        <a tabindex="0" class="deleteItemBtn btn btn-sm btn-outline-danger border-0" data-bs-trigger="focus" data-bs-toggle="popover" data-bs-title="Confirmer la suppression"  data-bs-content-id="popoverDelete{{userItem.id}}"><i class="bi bi-trash3-fill"></i>
                                        </a>
                                        
                                    </span>
                                    <div class="d-none">
                                        <div id="popoverDelete{{userItem.id}}" class="d-flex justify-content-between">
                                            <a class="btn btn-sm btn-secondary" href="#">Annuler</a>
                                            <a class="btn btn-sm btn-danger" href="{{path('app_item_delete', {id: userItem.id})}}">Confirmer</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endif %}
      </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
    {% block importmap %}
     {{ importmap(['app', 'itemIndex']) }}
    {% endblock %}
{% endblock %}

templates/app_item/item_list_component.html.twig
<ul class="list-group list-group-flush my-2">
  {% for userItem in userItems|slice(0,limit) %}
    <li class="list-group-item">{{userItem.property1}}</li>
  {% else %}
      <li class="list-group-item">Votre placard est vide</li>
  {% endfor %}
</ul>